version: "3"
services:

  mariadb:
    image: "mariadb:10.5"
    container_name: datacenter-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=datacenter
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: datacenter-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: cookie.develop
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 5672:5672
      - 15672:15672
